version: '3.7'

services:
  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    networks:
      - spark_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mspr3
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - spark_network

networks:
  spark_network:
    driver: bridge
    name: spark_network

volumes:
  pg_data:
    driver: local
